### PR TITLE
Add new article and update readme file

### PR DESCRIPTION
**Pull request by Mannuel25**
Hi @ProfCyberNaught , I have a suggestion as regarding how the articles are displayed in the readme file. What if they are displayed in a tabular format:

Here is an example showing the recent article I added:

| S/N | Title | Blog Link | GitHub Link | 
| --- | --- | --- | --- |
1| Cybersecurity: What is Malware? | [Link](https://profcybernaught.hashnode.dev/cybersecurity-what-is-malware)| [Link](https://github.com/Mannuel25/articles-blogs/blob/UpdatePagesContentHelp/cybersecurity-what-is-malware.md)| 

If you are okay with the suggestion I'd like to implement this.

### CODE REVIEW

**Review by ProfCyberNaught — CHANGES_REQUESTED** [review]
Hi Emmanuel.

Thank you kindly for making a contribution to this repository aimed at first timers. It would appear, you yourself are not a first timer to GitHub and are familiar with the inner-workings of this platform. May I ask why you have taken it upon yourself to make a pull request?

As for the changes made, I have the following review:

1) Within the README.md file, the link to the GitHub page actually points to your own folk branch, and not the main repo here.

2) Your link results in a 404 error because there has been a period added to your branch name. Even if this back-linking to a repo folk was accepted, it would still not work.

The above changes need to made before any acceptance of a merge can be made.

Regarding your suggestion to use a table to display the articles:

The idea had been considered originally when creating this repo. I was concerned with the length of certain article names, the layout, and more. I also do not like the idea of just having a hyperlink to the original source (the website) and GitHub page (this repo) named 'Link'. This does not help anybody, and certainly does not promote healthy SEO policies.

However, I would consider your proposal if you can address the concerns raised above.

I appreciate your time taken to carry out the pull request, the changes made, and your suggestion for the table. Looking forward to your response in due course.

**Comment by ProfCyberNaught** [comment]
Thanks for submitting the updated pull request. Before I accept the changes, are you wanting to address the table idea suggestion you made above?

**Comment by Mannuel25** [comment]
Hi @ProfCyberNaught , I've made the necessary corrections. Kindly let me know if I missed anything.
` May I ask why you have taken it upon yourself to make a pull request?` .. as for this, I've always been a fan of open-source ,and I'm always happy to contribute to projects, so when I saw that just a few blogs had been added to the repository, I plan to help out by adding the remaining articles that aren't present yet.

Then as for the table suggestion, unfortunately I couldn't come up with a better alternative. I'll bear this in mind, whenever I have an update on this I will do well to inform you.

**Comment by ProfCyberNaught** [comment]
Hi @Mannuel25 , I appreciate you getting back to me. Thank you for taking the time to add an article to the repository from the main website. I have reviewed your changes made and can see no issues with your submission moving forward. I would be glad to merge your request to the main branch.

As for the table idea, it is still a good idea. Regarding the link title being 'Link', maybe this could just be something that is considered in the future. However, if you wish to make the changes and add the table design instead to the README.md, please let me know and I will await the changes via this request. If not, let me know either way and I can complete the merge.

I noticed your CommunityPro and was wondering what this was all about, and if this is still active? I noticed, issues dating back months not addressed.

**Comment by ProfCyberNaught** [comment]
I have added the correct bold font types to the sectional titles, and the lists as per the original posted article on the main website.

https://profcybernaught.hashnode.dev/cybersecurity-what-is-malware

**Comment by Mannuel25** [comment]
Yeah, you can move with the merge for now.
CommunityPro stands for CommunityProject. It's basically a group of devs, designers coming together to work on projects, horn their skillsets and learn from each other. 
Then as for the issues not attended to, the project has been put on hold for now, they'll be attended when we continue.

**Comment by Mannuel25** [comment]
> I have added the correct bold font types to the sectional titles, and the lists as per the original posted article on the main website.
> 
> https://profcybernaught.hashnode.dev/cybersecurity-what-is-malware

Yeah, I took note of this, wanted to add it..i forgot eventually 😅 . Thanks for the correction.

**Review by ProfCyberNaught — APPROVED** [review]
I have reviewed the changes regarding the original review feedback. I have also added the bold font type that had been missed from the original article post over on the main website. I see no issue merging the branches.

**Comment by ProfCyberNaught** [comment]
Regarding the table suggestion mentioned within this pull request, I have implemented the solution factoring in the additional SEO clarifications mentioned:

| Title | Blog Link | GitHub Link | 
| --- | --- | --- |
| Why Become A Cybersecurity Engineer? | [Link](https://profcybernaught.hashnode.dev/why-become-a-cybersecurity-engineer "Why Become A Cybersecurity Engineer?")| [Link](https://github.com/ProfCyberNaught/articles-blogs/blob/main/why-become-a-cybersecurity-engineer.md "Why Become A Cybersecurity Engineer?")|

If you hover over the links, you will see the additional title tags further supporting SEO Best Practices. The structure of the link would be as follows:

[ <Article Title> ] [ <Link Name> ( <Blog Link URL> " <Link Title Tag> " ) ]

Hope this helps for future reference.

**Comment by Mannuel25** [comment]
This works perfectly!

**Comment by ProfCyberNaught** [comment]
Just to let you know, I have created a column where contributors can place their GitHub Profile name, with a link back to their profile on the main README.md table. Thanks for your contributions. I have added yours already.

**Comment by Mannuel25** [comment]
> Just to let you know, I have created a column where contributors can place their GitHub Profile name, with a link back to their profile on the main README.md table. Thanks for your contributions. I have added yours already.

Okay, thank you!

**Comment by ProfCyberNaught** [comment]
<ins>**IMPORTANT NOTICE:**</ins> The requirements for contributing to this repository have been updated along with the steps and information relating to it. Please check the new issue: [MAKE AN ARTICLE COPY ISSUE](https://github.com/ProfCyberNaught/cybersecurity-blog-posts/issues/43 "MAKE AN ARTICLE COPY ISSUE - ProfCyberNaught - Cybersecurity Blog")

**Pull request merged**
